# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-fibonacci
# >> macros
%define _binary_payload w2.xzdio
%define __provides_exclude_from ^%{_datadir}/%{name}/lib/.*\\.so\\>
%define __requires_exclude_from ^%{_datadir}/%{name}/lib/.*\\.so\\>
# << macros

%{!?harbour_store:%define harbour_store %(if [ -n "$HARBOUR_STORE" ]; then echo 1; elif echo "$PWD" | grep -q -- '-Store'; then echo 1; else echo 0; fi)}

# flip with and without to locally build as it would on chum
%if 0%{?harbour_store}
%bcond_with harbour
%else
%bcond_without harbour
%endif

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}

Summary:    RPN Calculator with exprtk programmable interface for SailfishOS.
Version:    1.0.4
Release:    1
Group:      Qt/Qt
License:    GPL
URL:        https://github.com/poetaster/fibonacci
Source0:    %{name}-%{version}.tar.bz2

Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   pyotherside-qml-plugin-python3-qt5 >= 1.3.0

%if %{without harbour} ||  "%{?vendor}" == "chum"
Requires:   jolla-keyboard
%endif

%if "%{?vendor}" == "chum"
BuildRequires:  python3-setuptools_scm
%endif

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  python3-rpm-macros
BuildRequires:  python3-setuptools
BuildRequires:  python3-base
BuildRequires:  python3-devel

%description
Full symbolic RPN calculator using Sympy with a programmable calculator using exprtk c++.
Based in part on https://github.com/lainwir3d/sailfish-rpn-calculator

%if "%{?vendor}" == "chum"
PackageName: fibonacci
Type: desktop-application
Categories:
 - Science
 - Utility
DeveloperName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/poetaster/fibonacci
Icon: https://raw.githubusercontent.com/poetaster/fibonacci/main/icons/172x172/harbour-fibonacci.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/fibonacci/main/screenshot-1.png
 - https://raw.githubusercontent.com/poetaster/fibonacci/main/screenshot-2.png
 - https://raw.githubusercontent.com/poetaster/fibonacci/main/screenshot-3.png
Url:
  Donation: https://www.paypal.me/poetasterFOSS
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%if %{without harbour} || "%{?vendor}" == "chum"
 %qmake5
%else
 %qmak5 CONFIG+=harbour_store
%endif


%install
# >> install pre
# << install pre
%qmake5_install

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

 mkdir -p %{buildroot}%{_datadir}/%{name}/python

cd %{buildroot}%{_datadir}/%{name}/lib/sympy-1.9
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf  %{buildroot}%{_datadir}/%{name}/lib/sympy-1.9

cd %{buildroot}/%{_datadir}/%{name}/lib/pyparsing-2.4.7
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/lib/pyparsing-2.4.7

cd %{buildroot}/%{_datadir}/%{name}/lib/mpmath-1.3.0
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/lib/mpmath-1.3.0

cd %{buildroot}/%{_datadir}/%{name}/lib/dice-1.0.2
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
rm -rf %{buildroot}/%{_datadir}/%{name}/lib/dice-1.0.2

rm -rf %{buildroot}/%{_datadir}/%{name}/share
rm -rf %{buildroot}/%{_datadir}/%{name}/bin

cd %_builddir

%if %{without harbour} || "%{?vendor}" == "chum"
%post
# >> post
killall maliit-server
# << post
%postun
# >> postun
killall maliit-server
# << postun
%endif

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%if %{without harbour} || "%{?vendor}" == "chum"
%{_datadir}/maliit/plugins/com/jolla/layouts/programmers.qml
%{_datadir}/maliit/plugins/com/jolla/layouts/layouts_programmers.conf
%endif

# >> files
# << files
